Fix for circles coloring of a transformer inside a voltage level
powsybl/powsybl-diagram pull request #224
Opened 2021-02-15 14:53 UTC by SlimaneAmar

Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Bug fix

**What is the current behavior?** *(You can also link to an open issue here)*
Circles of a transformer inside a voltage level are not coloried with the topology style provider

**What is the new behavior (if this is a feature change)?**
Circles of a transformer inside a voltage level are now coloried with the topology style provider

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*
No

2021-03-22 10:00 UTC, floriand-e2r requested changes

2021-03-22 10:00 UTC, floriand-e2r commented on single-line-diagram-core/src/test/resources/TestCase12GraphWithNodesInfosTopological.svg
>              </g>
The fact that you needed to change this test reference shows that your modifications introduced some regressions. The feeders in the test are not disconnected.

2023-02-01 15:21 UTC, flo-dup commented
This can now be closed following #493: nodes which might get several colors have one subComponent for each color. The side is then known thanks to `AbstractBaseVoltageDiagramStyleProvider::getSide(subComponentName)`. With the side, the style is then known by getting the style of the adjacent node on this side.

2023-02-01 15:21 UTC, closed without merging

2023-02-01 15:25 UTC, SlimaneAmar commented
Done