237 animate feeder arrows
powsybl/powsybl-diagram pull request #500
Opened 2023-02-13 09:28 UTC by tadam50

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*
#237

2023-02-13 16:42 UTC, tadam50 commented
Breaking changes is raised here by adding new parameter into 
`public List<String> getFeederInfoStyles(FeederInfo info, boolean animated)`
This new parameter is used to give `LayoutParameter::isEnableFeederInfosAnimation()`

2023-02-14 16:24 UTC, So-Fras requested changes
Thank you for your work so far. We must clear up some specifications for you to be able to go on with the development.
Moreover, we did not realize at first that this feature could bring a breaking change.

2023-02-14 16:24 UTC, So-Fras commented on single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/svg/DiagramStyles.java
> +    public static final String ARROW_ANIMATION_SPEED_1 = STYLE_PREFIX + "arrow-animation-speed-1";
We have to decide how to discretize the power values and maybe include  "no value" or "zero power" cases.

2023-02-23 13:59 UTC, So-Fras requested changes
I made very few comments. Thank you for your nice work!

2023-02-23 13:59 UTC, So-Fras commented on single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/util/AnimatedFeederInfoStyleProvider.java
> +    private static final String ARROW_ANIMATION_NOMINAL_SPEED = ARROW_ANIMATION + "-nominal-" + ARROW_SPEED;
I would not call it "nominal" but "average" maybe.

2023-02-23 13:59 UTC, So-Fras commented on single-line-diagram/single-line-diagram-core/src/main/resources/animations.css
> +.sld-arrow-animation-nominal-speed { --sld-arrow-animation-duration: 2s }
If you change the name from "nominal" to "average", it will have an impact here too!

2023-03-02 12:42 UTC, So-Fras approved these changes
Everything is OK for me!

2023-03-20 16:14 UTC, flo-dup requested changes

2023-03-20 16:14 UTC, flo-dup commented on single-line-diagram/single-line-diagram-core/src/test/resources/TestAnimatedFeederInfos.svg
This file is not working on my firefox 96.0, the bottom black arrow is pointing to the top instead of to the bottom. It seems that the rotate is overriden. But in [the specifications](https://drafts.fxtf.org/motion-1/#offset-rotate-property) it is written that:
> Note: The rotation described here does not override or replace any rotation defined by the [transform](https://drafts.csswg.org/css-transforms-1/#propdef-transform) property.

So, if it still occurs on a more recent version of firefox, we should report it to mozilla bug report.

2023-03-23 14:44 UTC, tadam50 commented on single-line-diagram/single-line-diagram-core/src/test/resources/TestAnimatedFeederInfos.svg
On Firefox ESR 102.9.0 (March 14, 2023) same issue

2023-03-23 16:43 UTC, flo-dup reviewed
Just 2 typos and we're good!

2023-03-27 18:11 UTC, flo-dup approved these changes

2023-03-27 18:19 UTC, merged