Add parameter to disable/enable internal 2wt
powsybl/powsybl-diagram pull request #594
Opened 2024-03-13 13:48 UTC by flo-dup

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
No

**What kind of change does this PR introduce?**
Bug fix / feature

**What is the current behavior?**
Internal two-winding transformers and phase-shift transformers are added in VoltageLevelGraph as `EquipmentNode`s, hence are withing an InternCell or ExternCell.

**What is the new behavior (if this is a feature change)?**
Internal two-winding transformers and phase-shift transformers are added in VoltageLevelGraph as `FeederNode`s, but can be later replaced by `EquipmentNode`s with VoltageLevelLayoutFactoryParameter::setSubstituteInternalMiddle2wtByEquipmentNodes`. This parameter is true by default.

**Other information**:
`NetworkGraphBuilder::handleConnectedComponents` (together with child method `NetworkGraphBuilder::ensureOneBusInConnectedComponent`) needed to move to `GraphRefiner` in order not to interfere with this feature

2024-03-14 12:59 UTC, geofjamg approved these changes

2024-03-14 21:03 UTC, So-Fras requested changes

2024-03-15 10:04 UTC, flo-dup commented on single-line-diagram/single-line-diagram-core/src/test/java/com/powsybl/sld/iidm/TestInternalBranchesNodeBreaker.java
> +        new PositionVoltageLevelLayoutFactory(new PositionFromExtension(), pvllfParameters).create(g).run(this.layoutParameters);
I prefer to put this explicitly, as this default choice does not seem clear to me. And I'd like to remove one day that constructor which assumes that it should be a PositionFromExtension by default (without any javadoc specifying it!)

2024-03-15 10:40 UTC, So-Fras approved these changes

2024-03-15 12:15 UTC, merged