In the single line diagram of a substation, each voltage level's style index now starts at zero
powsybl/powsybl-diagram pull request #633
Opened 2024-07-12 12:11 UTC by EstherDarkish

**Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

No.

**What kind of change does this PR introduce?**

Fixes the discrepancy of style applied to buses between a voltage level and the same voltage level in a substation.

**What is the current behavior?**

When a voltage level is displayed inside a substation and if the voltage level shares a nominal voltage with another voltage level in the substation, then the voltage level's buses' colors do not match the colors of this same voltage level displayed by itself in another SLD.

**What is the new behavior (if this is a feature change)?**
When drawing a substation's SLD, the styles applied to the voltage level's buses are consistent with the styles used when the voltage level is displayed by itself in another SLD.

**Does this PR introduce a breaking change or deprecate an API?**
- [x] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [x] The *Breaking Change* or *Deprecated* label has been added
- [x] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

Because the SVG generated when drawing a SLD are fixed, users might need to check that the new colors do not break their unit tests.

**Other information**:

2024-07-16 11:34 UTC, flo-dup commented
I'm not fully convinced by the resulting diagrams. When using TopologicalStyleProvider, one expects one colour for each electrical node. With this dev, in substation diagrams two nodes might have the same colour but different voltage and angle values. That implies there cannot be a single legend ("NodesInfo") in a substation diagram.

2024-08-09 13:22 UTC, flo-dup commented
I understand the need here (the user requires that one bus has the same colour in the substation diagram as in the votlage level diagram), but I think some users might want different colours for each electrical node displayed in the substation diagram. So we'd better add a parameter inside SvgParameter (which needs to be passed to TopologicalyStyleProvider) to enable/disable this behaviour.

2024-10-08 15:08 UTC, flo-dup requested changes

2024-10-09 15:00 UTC, EstherDarkish commented on single-line-diagram/single-line-diagram-core/src/main/java/com/powsybl/sld/SldParameters.java
> +    public StyleProvider createStyleProvider(Network network) {
What about the createLabelProvider just above (line 70) ? This was inspired by it

2024-10-10 09:31 UTC, flo-dup approved these changes

2024-10-10 09:34 UTC, merged